config/routes.rb
Rails.application.routes.draw do
  resources :dogs
  root 'dogs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dog_params)
    if @dog.save
      redirect_to dogs_path
    else
      render :new
    end
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :breed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/index.html.erb
<h1>All the dogs</h1>

<% @dogs.each do |dog| %>
  <p><%= link_to dog.name, dog_path(dog) %></p>
<% end %>

app/views/dogs/new.html.erb
<%= form_for @dog do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.text_field :breed %>
  <%= f.submit %>
<% end %>

app/views/dogs/show.html.erb
<h3><%= @dog.name %> the dog.</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dogs1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>